import type { Metadata } from "next"
import {
    Geist,
    Geist_Mono,
    Inter,
    Montserrat,
    Noto_Sans,
    Raleway,
} from "next/font/google"
import "./globals.css"
import Navbar from "@/components/navbar"
import { ThemeProvider } from "next-themes"

const inter = Raleway({
    variable: "--font-raleway",
    subsets: ["latin"],
})
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`antialiased ${inter.className}`}>
                <ThemeProvider attribute={"class"} enableSystem>
                    <Navbar />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    )
}
