import type { Metadata } from "next"
import { Raleway } from "next/font/google"
import "./globals.css"

import { ThemeProvider } from "next-themes"
import { getSession } from "@/lib/session"
import NavbarWrapper from "@/components/NavbarWrapper"

const inter = Raleway({
    variable: "--font-raleway",
    subsets: ["latin"],
})
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const session = await getSession()
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`antialiased ${inter.className}`}>
                <ThemeProvider attribute={"class"} enableSystem>
                    {!session ? <NavbarWrapper /> : null}
                    {children}
                </ThemeProvider>
            </body>
        </html>
    )
}
